#!/usr/bin/env python
configfile = "/opt/transfers/dataFlowEoR.conf"
pidFile ="/var/run/dfEoR.pid"

import sys, os, socket, signal, pprint
from Daemon import Daemon

from configobj import ConfigObj
from Logging_EoR import getLogger
import eor

logger = getLogger()

def getTransferParams(transferConfigFileName):
    try:
        if os.path.isfile(transferConfigFileName):
            config = ConfigObj(transferConfigFileName)
        else:
            logger.error("Configuration file not found: {0}!".format(transferConfigFileName))
            sys.exit(1)
    except IOError, e:
        logger.error("Unable to open configuration file: {0}!".format(transferConfigFileName))
        sys.exit(1)

    return config

class DataFlowEoR(Daemon):
    running = True

    def cleanUp(self, sigNum = None, frame = None):
        logger.debug('Cleaning up...')
        if os.path.isfile(self.pidfile):
            os.remove(self.pidfile)
        self.running = False

    def run(self):
        
        params = getTransferParams(configfile)
        logger.info(
            "You are now running: eor.main({0})".format(
                pprint.pformat(params)
            )
        )
        eor.main()

if __name__ == "__main__":

    daemon = DataFlowEoR(pidFile)

    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'status' == sys.argv[1]:
            daemon.status()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "Usage: %s start|stop|restart|status" % sys.argv[0]
        sys.exit(2)
