#!/usr/bin/env python
#configfile = "/opt/python/transfer/hook/dataFlowTransfer.conf"
#configfile = "/nfshome0/zdemirag/DAQ/transfers/transfer-hook/service/dataFlowTransfer.conf"
#configfile = "/opt/transfers/dataFlowTransfer.conf"
configfile  = "/opt/transfers/smhookd.conf"
pidFile ="/var/run/dfTransfer.pid"

import sys, os, socket, signal, pprint
from Daemon import Daemon

from Logging import getLogger
import config
import watchAndInject

logger = getLogger()


class DataFlowTransfer(Daemon):
    running = True

    def cleanUp(self, sigNum = None, frame = None):
        logger.debug('Cleaning up...')
        if os.path.isfile(self.pidfile):
            os.remove(self.pidfile)
        self.running = False

    def run(self):
        config.init(configfile)
        logger.info("You are now running: watchAndInject.main()")
        watchAndInject.main()

if __name__ == "__main__":

    daemon = DataFlowTransfer(pidFile)

    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'status' == sys.argv[1]:
            daemon.status()
        else:
            print "Unknown command"
            sys.exit(2)
        sys.exit(0)
    else:
        print "Usage: %s start|stop|restart|status" % sys.argv[0]
        sys.exit(2)
