#! /bin/bash
#
# hellod       Init file used for starting / stoppping the SM hook daemon.
#
# chkconfig: 2345 85 25
# description: The service that hooks the merger to the SM transfer system.
# processname: smhookd
# pidfile: /var/run/smhookd.pid

# Source function library.
. /etc/rc.d/init.d/functions

PROG="smhookd.py"

PROG_PATH="/opt/python/smhook/$PROG"
RETVAL=0
export PYTHONPATH=/opt/python

# See how we were called.
case "$1" in
  start)
        echo -n "Starting $PROG: "
        $PROG_PATH start > /dev/null
        RETVAL=$?
        [ $RETVAL -eq 0 ] && success "$PROG startup" || failure "$PROG startup"
        echo
        ;;
  stop)
        echo -n "Stopping $PROG: "
        $PROG_PATH stop > /dev/null
        RETVAL=$?
        [ $RETVAL -eq 0 ] && success "$PROG stop" || failure "$PROG stop"
        echo
        ;;
  kill)
        echo -n "Killing $PROG: "
        $PROG_PATH kill > /dev/null
        RETVAL=$?
        [ $RETVAL -eq 0 ] && success "$PROG kill" || failure "$PROG kill"
        echo
        ;;
  status)
        $PROG_PATH status
        RETVAL=$?
        ;;
  restart)
        $0 stop
        $0 start
        RETVAL=$?
        ;;
  *)
        echo "Usage: $PROG {start|stop|kill|status|restart}"
        exit 1
esac

exit $RETVAL

